import { WaterBrand } from "../types/water";

export const MOCK_WATERS: WaterBrand[] = [
    {
        id: "1",
        name: "Erikli",
        country: "TR",
        flagEmoji: "🇹🇷",
        ph: 7.5,
        tds: 108,
        sourceType: "spring",
        likes: 1250,
        rating: 4.8,
        ratingCount: 450,
        minerals: {
            calcium: 12.5,
            magnesium: 3.2,
            sodium: 1.8,
            potassium: 0.5,
            bicarbonate: 68.0,
        },
        createdAt: new Date(),
    },
    {
        id: "2",
        name: "Evian",
        country: "FR",
        flagEmoji: "🇫🇷",
        ph: 7.2,
        tds: 345,
        sourceType: "mineral",
        likes: 3400,
        rating: 4.6,
        ratingCount: 890,
        minerals: {
            calcium: 80.0,
            magnesium: 26.0,
            sodium: 6.5,
            potassium: 1.0,
            bicarbonate: 360.0,
            sulfate: 14.0,
            chloride: 10.0,
        },
        createdAt: new Date(),
    },
    {
        id: "3",
        name: "Fiji",
        country: "FJ",
        flagEmoji: "🇫🇯",
        ph: 7.7,
        tds: 222,
        sourceType: "artesian",
        likes: 5600,
        rating: 4.9,
        ratingCount: 1200,
        minerals: {
            calcium: 18.0,
            magnesium: 15.0,
            sodium: 18.0,
            potassium: 5.0,
            bicarbonate: 152.0,
            fluoride: 0.2,
        },
        createdAt: new Date(),
    },
];
